

### Add a spotti to users spottis
PATCH http://authservice.dev/users/1/spottis
content-type: application/json

{
  "spottiId": 7
}

### Get user's spottis
GET http://authservice.dev/users/1/spottis
