apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
  storageClassName: gp2  # Use AWS General Purpose SSD storage class (or gp3 for newer EBS volumes)
