apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotti-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust based on your needs
  storageClassName: gp2  # Use AWS General Purpose SSD storage class
