export enum Category {
  Nearby = 'Nearby',
  Landmarks = 'Landmarks',
  Historical = 'Historical',
  Parks = 'Parks',
  FamousStreets = 'Famous Streets',
  Museums = 'Museums',
  NaturalWonders = 'Natural Wonders',
  Beaches = 'Beaches',
  Entertainment = 'Entertainment',
  Shopping = 'Shopping',
  Dining = 'Dining',
  Dessert = 'Dessert',
  ScenicViews = 'Scenic Views',
  Churches = 'Churches',
  Monuments = 'Monuments',
  NightLife = 'Night Life',
  Aquariums = 'Aquariums',
  GolfCourses = 'Golf Courses',
  Zoos = 'Zoos',
  Theaters = 'Theaters',
  CoffeeShops = 'Coffee Shops',
  SportsArenas = 'Sports Arenas'
}