apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /Users/nathanschrader/hub-sqlite-db # Path on the host machine for Hub service's DB

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: hub-sqlite-pv