### Create a new user
POST http://authservice.dev/auth/signup
content-type: application/json

{
  "firstName": "Nathan",
  "lastName": "Schrader",
  "email": "user100@email.com",
  "password": "user1"
}

