### say hello
POST http://authservice.dev/spottis
Content-Type: application/json

{
  "name": "NW Grapefruit Street",
  "description": "Great food in the NW part of Porltand",
  "locationId": "302",
  "category": "Famous Streets",
  "rating": 4,
  "tags": ["shopping", "dining"],
  "reviews": [],
  "pictures": ["pic1.png", "pic2.png"],
  "bestTimeToVisit": "afternoon",
  "hoursOfOperation": "9am-5pm",
  "nearbySpottis": []
}

### Test endpoint
GET http://authservice.dev/spottis/test

### Get one spotti
GET http://authservice.dev/spottis/1

### Get all spottis
GET http://authservice.dev/spottis